build: init & fix of mdx needs source-filesystem
build: use only source-git online & fs local

build: rename dir VideoPlayer>react-video-player

build(netlify): [debug] disable VideoPlayer

build(netlify): [debug] disable rehype-slug

build(netlify): [debug] disable gatsbyRemarkPlugins

build(netlify): [debug] enable mdx, use forked gatsby

build(netlify): [debug] log less in gatsby nodes.js

build(netlify): [debug] slim down log in gatsby nodes.js

build(netlify): [debug] log node&store if require fails

build(netlify): somethings overriding ruby version, this redos it

build(netlify): setting ruby version to default

build(netlify): remove ruby version, not working & sthg needs..

the other version it seems?!

build(gatsby): always include source-fs, fixes mdx resolve issue..

error Plugin gatsby-mdx returned an error
TypeError: Cannot read property 'resolve' of undefined
- nodes.js:50 resolve
  [repo]/[gatsby]/dist/db/nodes.js:50:40
- new Promise
- nodes.js:46 module.exports.loadNodeContent.node
  [repo]/[gatsby]/dist/db/nodes.js:46:12
- on-create-node.js:50 Object.module.exports [as onCreateNode]
  [repo]/[gatsby-mdx]/gatsby/on-create-node.js:50:25

chore: remove local gatsby debug fork & reinstall gatsby